"""Generate JSON and Markdown reports from a completed ScanState."""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

from .checks import ScanState

SEV_ICON = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🔵"}


def save_json(state: ScanState, path: str) -> Path:
    out = Path(path)
    data = {
        "tool": "MCPPT",
        "version": "2.0.0",
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "target": state.url,
        "elapsed_seconds": round(state.elapsed, 1),
        "summary": {
            sev: sum(1 for f in state.findings if f.severity == sev)
            for sev in ("CRITICAL", "HIGH", "MEDIUM", "LOW")
        },
        "findings": [
            {
                "check": f.check,
                "severity": f.severity,
                "title": f.title,
                "detail": f.detail,
            }
            for f in state.findings
        ],
    }
    out.write_text(json.dumps(data, indent=2), encoding="utf-8")
    return out


def save_markdown(state: ScanState, path: str) -> Path:
    out = Path(path)
    ts = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        "# MCPPT Security Scan Report",
        "",
        f"**Target:** `{state.url}`  ",
        f"**Date:** {ts}  ",
        f"**Duration:** {state.elapsed:.1f}s  ",
        "",
        "## Summary",
        "",
        "| Severity | Count |",
        "| --- | --- |",
    ]
    for sev in ("CRITICAL", "HIGH", "MEDIUM", "LOW"):
        count = sum(1 for f in state.findings if f.severity == sev)
        lines.append(f"| {SEV_ICON[sev]} {sev} | {count} |")

    lines += ["", "## Findings", ""]

    if not state.findings:
        lines.append("_No findings detected — all checks passed._")
    else:
        for i, f in enumerate(state.findings, 1):
            icon = SEV_ICON.get(f.severity, "⚪")
            lines += [
                f"### {i}. {icon} [{f.severity}] {f.title}",
                "",
                f"**Check:** `{f.check}`  ",
                f"**Severity:** {f.severity}  ",
                "",
                f.detail,
                "",
                "---",
                "",
            ]

    lines += [
        "## Remediation Reference",
        "",
        "| Check | Risk | Fix |",
        "| --- | --- | --- |",
        "| `enum` | Info disclosure | Require auth on `tools/list` |",
        "| `auth` | Auth bypass | Validate Bearer token server-side on every tool call |",
        "| `idor` | Data exposure | Scope resource access to the authenticated user |",
        "| `injection` | Prompt injection | Sanitise/escape all user-supplied strings before returning to LLM |",
        "| `schema` | Input validation | Enforce strict type validation at the MCP server layer |",
        "| `ssrf` | SSRF | Block RFC-1918/link-local URLs; use allowlist for external fetches |",
        "| `publish` | Unconfirmed action | Enforce confirmation gate in MCP layer, not only in agent prompt |",
        "| `rate` | DoS | Add rate limiting per token/IP |",
        "| `stored` | Stored injection | Escape stored content before returning in tool responses |",
        "| `scope` | Privilege escalation | Enforce token scopes server-side per tool |",
        "| `replay` | Replay | Add per-request nonce or timestamp window validation |",
        "| `context_overflow` | Context hijack | Enforce max field length at ingestion |",
        "| `poison_all` | Injection | Sanitise every response field, not just primary content |",
        "| `tenant` | Data leak | Scope cache keys and storage to tenant/user ID |",
        "| `session` | Session hijack | Use CSPRNG ≥128-bit entropy for session IDs (UUID v4) |",
        "| `rug_pull` | Supply chain | Pin tool versions; alert on description changes |",
        "",
        "---",
        "_Generated by [MCPPT](https://github.com/gurudeepmallam-cmd/mcppt) v2.0_",
    ]

    out.write_text("\n".join(lines), encoding="utf-8")
    return out
